### PR TITLE
added module response codes to the query response objects

### PR DESCRIPTION
**Pull request by andreasjberg**
A basic little start of making module error codes visible to the browser plugin

### CODE REVIEW

**Comment by andreasjberg** [comment]
The module_response_code object is a map with the name of the module as key and the http status code as value

**Comment by davidsalvador** [comment]
My understanding was that the API Gateway does not return each module's response to the Browser Plugin. What it returns instead, is the output of the Rule Engine.

Am I missing something?

**Comment by daffyDukk** [comment]
@davidsalvador 
you are not missing anything. This is a bit of extra information for all of us. If you find a responsecode that is NOT 200 (HTTPstatus OK) we can both check what could have gone wrong...

Since the gateway does very little introspection of what gets passed around this would help debugging on all ends.

**Comment by davidsalvador** [comment]
I see. Then, if any module returns a non-200 response, the Gateway will stop the processing and return that to the Browser Plugin, is that correct?

Maybe this is off-topic but we should start considering what to do when one Misinformation Detection Module (Misinfome, etc.) fails. Do we still provide to Rule Engine with other outputs? Will the Rule Engine support that, etc.

**Comment by daffyDukk** [comment]
thats the general idea.
THe gateway will pass the errorcode and whatever else it has if other modules where successfull. We think this would make it easier to debug on all ends, since we would be able to see which module produces what error.

**Comment by davidsalvador** [comment]
If this is for an early stage debugging mechanism then ok. Otherwise, I think that the response given to the Browser Plugin should only be the Rule Engine's output.

**Review by davidsalvador — APPROVED** [review]

**Review by daffyDukk — APPROVED** [review]

**Pull request merged**
